module.exports = {
  apps: [
    {
      name: 'whatsapp-worker',
      script: './src/index.js',
      cwd: '/opt/jeff-worker',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      kill_timeout: 15000,
      wait_ready: true,
      listen_timeout: 30000,
      out_file: './logs/out.log',
      error_file: './logs/err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'agent-runner',
      script: './scripts/agent-runner.sh',
      cwd: '/opt/jeff-worker',
      interpreter: 'bash',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      out_file: './logs/agent-runner.out.log',
      error_file: './logs/agent-runner.err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        HOME: '/root',
        PATH: '/root/.nvm/versions/node/v20.20.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      },
    },
    {
      name: 'cigc-monitor',
      script: './scripts/cigc-monitor.sh',
      cwd: '/opt/jeff-worker',
      interpreter: 'bash',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '100M',
      out_file: './logs/cigc-monitor.out.log',
      error_file: './logs/cigc-monitor.err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        HOME: '/root',
        PATH: '/root/.nvm/versions/node/v20.20.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      },
    },
    {
      name: 'farias-monitor',
      script: './scripts/farias-monitor.sh',
      cwd: '/opt/jeff-worker',
      interpreter: 'bash',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '100M',
      out_file: './logs/farias-monitor.out.log',
      error_file: './logs/farias-monitor.err.log',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        HOME: '/root',
        PATH: '/root/.nvm/versions/node/v20.20.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      },
    },
  ],
};
